export enum PreviewTemplateId {
  FULL_S_IL_TR = "FULL_S_IL_TR",
  FULL_M_IL_TR = "FULL_M_IL_TR",
  FULL_L_IL_TR = "FULL_L_IL_TR",
  FULL_S_IR_TL = "FULL_S_IR_TL",
  FULL_M_IR_TL = "FULL_M_IR_TL",
  FULL_L_IR_TL = "FULL_L_IR_TL",
  FULL_L_IL_TB = "FULL_L_IL_TB",
  FULL_XL_IL_TB = "FULL_XL_IL_TB",
  FULL_L_IR_TB = "FULL_L_IR_TB",
  FULL_XL_IR_TB = "FULL_XL_IR_TB",
}