export enum SectionIds {
  MAIN_BRAND_ART = "MAIN_BRAND_ART",
  HEADER = "HEADER",
  COS_ART = "COS_ART",
  COS_TEXT = "COS_TEXT",
  COS_VIDEO = "COS_VIDEO",
  TAM_ART = "TAM_ART",
  TAM_TEXT = "TAM_TEXT",
  COS_TAM_VIDEO = "COS_TAM_VIDEO",
  MISSION_TEXT = "MISSION_TEXT",
  ABOUT_TEXT = "ABOUT_TEXT",
  CONTACT = "CONTACT"
}